<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>All offerings</title>

</head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <!-- Using Bootstrap CSS -->

    <link rel="stylesheet" href="/../style.css">


<body>
    <nav class="navbar bg-body-tertiary" style="padding-top: 0%; padding-bottom: 0%; justify-content: space-between;">
  <div class="container-fluid" style="background-color: #2a5726;">
    <a class="navbar-brand" href="#">
      <img src="/../images/trailbuddy_logo.png" alt="Logo" width="60" height="70" class="d-inline-block align-text-center"><span>TrailBuddy</span>
    </a>
    <a href="/provider/providerProfile" class="btn btn-success" style="margin-left: 1450px;">Profile</a>
    <a href="/provider/login" class="btn btn-secondary" style="margin-right: 27px;">Logout</a>
  </div>
</nav>

<div class="card-container" style="padding-bottom: 265px;">

            <!--Activity #1-->
            <div class="card">
                
                <img>
                <h2>Activity 1</h2>
                <p>
                    Skill Level: 
                    <span class="tag">
                        Beginner
                    </span>
                </p>

                <p>
                    Description
                </p>
                <p> Location</p>
                <p> Date</p>
                <p>Gear list</p>
                <div class="btn-group" role="group" aria-label="Basic mixed styles example">
  <button type="button" class="btn btn-danger">Remove</button>
  <button type="button" class="btn btn-warning">Update</button>
</div>
            </div>

             <!--Activity #2-->
           <div class="card">
                
                <img>
                <h2>Activity 2</h2>
                <p>
                    Skill Level: 
                    <span class="tag">
                        Intermediate
                    </span>
                </p>

                <p>
                    Description
                </p>
                <p> Location</p>
                <p> Date</p>
                <p>Gear list</p>
                <div class="btn-group" role="group" aria-label="Basic mixed styles example">
  <button type="button" class="btn btn-danger">Remove</button>
  <button type="button" class="btn btn-warning">Update</button>
</div>
</div>
            <!--Activity #3-->
            <div class="card">
                
                <img>
                <h2>Activity 3</h2>
                <p>
                    Skill Level: 
                    <span class="tag">
                        Expert
                    </span>
                </p>

                <p>
                    Description
                </p>
                <p> Location</p>
                <p> Date</p>
                <p>Gear list</p>
                <div class="btn-group" role="group" aria-label="Basic mixed styles example">
  <button type="button" class="btn btn-danger">Remove</button>
  <button type="button" class="btn btn-warning">Update</button>
</div>


        </div>
    </div>

<footer>
        <p>@ 2026 TrailBuddy</p>
    </footer>
</body>
</html>