<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="/../style.css">
</head>


<body>
    
    <form method="post">
    <div class="login-container">

        <div class="login-box">
            <div class="logo">
                <img src="/../images/trailbuddy_logo.png" alt="">
            </div>
            <h3>TrailBuddy</h3>
            <p>Explore. Discover. Adventure.</p>

            <input type="email" placeholder="Email">

            <input type="password" placeholder="Password">

            <a href="#"><button>Login</button>
            </a>

            <p><a href="providerSignup.html">Don't have an account?-sign up as provider</a></p>
            <p><a href="customerSignup.html">Don't have an account?-sign up as a customer</a></p>

        </div>

    </div>
    </form>

</body>


</html>