<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="/style.css">
</head>


<body>

    <form action="/login" method="post">
        <div class="login-container">

            <div class="login-box">
                <div class="logo">
                    <img src="/../images/trailbuddy_logo.png" alt="">
                </div>
                <h3>TrailBuddy</h3>
                <p>Explore. Discover. Adventure.</p>

                <input type="email" id="email" name="email" placeholder="Email">

                <input type="password" id="password" name="password" placeholder="Password">

                <button type="submit">Login</button>
    </form>

    <p><a href="/provider/signup">Don't have an account?-sign up as provider</a></p>
    <p><a href="/customer/signup">Don't have an account?-sign up as a customer</a></p>

    </div>

    </div>


</body>


</html>